apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: database
    tier: backend
spec:
  template:
    metadata:
      labels:
        app: database-pod
        tier: backend-pod
    spec:
      containers:
        - name: myslq-container
          image: mysql
          env:
          - name: MYSQL_ROOT_PASSWORD
            value: password

  serviceName: mysql-cluster
  replicas: 3
  selector:
    matchLabels:
      app: database-pod
---

apiVersion: v1
kind: Service
metadata:
  name: mysql-cluster
spec:
  ports:
    - port: 3306
  selector:
    app: database-pod
    tier: backend-pod
  clusterIP: None
