apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  labels:
    app: database
    tier: backend
spec:
  template:
    metadata:
      labels:
        app: database-pod
        tier: backend-pod
    spec:
      containers:
        - name: myslq-container
          image: mysql

  serviceName: mysql-cluster
  replicas: 3
  selector:
    matchLabels:
      app: database-pod
