apiVersion: batch/v1
kind: CronJob
metadata:
  name: math-add-job-cron
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      completions: 3
      parallelism: 3
      template:
        spec:
          containers:
            - name: match-add
              image: kodekloud/random-error
              command: ['expr', '3', '+', '2']
          restartPolicy: Never
