apiVersion: batch/v1
kind: Job
metadata:
  name: math-add-job
spec:
  completions: 3
  parallelism: 3
  template:
    spec:
      containers:
        - name: match-add
          image: kodekloud/random-error
          command: ['expr', '3', '+', '2']
      restartPolicy: Never
