apiVersion: v1
kind: Pod
metadata:
  name: random-number
spec:
  containers:
    - name: random-alpine
      image: alpine
      command: ["/bin/sh", "-c"]
      args: ["echo 123 >> /opt/number.out;"]
      volumeMounts:
        - mountPath: /opt
          name: data-volume

  volumes:
    - name: data-volume
      persistentVolumeClaim:
        claimName: myclaim
